@startuml

class CSimpleFactory {
    CreateOperate(sOperate)
}

class COperation {
    m_iNumberA
    m_iNumberB
}

CSimpleFactory <-- COperation
COperation <|-- CAdd
COperation <|-- CSub
COperation <|-- CMul
COperation <|-- CDiv

@enduml